一道題目3小題
1.假設有一筆資料scores = {'Math':[90,np.nan,70,80],
                 'English':[60,70,'90',50],
                 'History':[33,np.nan,188,60]}
請先將它匯入至df df = pd.DataFrame(scores, index=['Simon','Allen','Jimmy','Peter'])

In [22]:
import pandas as pd
import numpy as np

In [39]:
scores = {'Math':[90,np.nan,70,80], 'English':[60,70,'90',50], 'History':[33,np.nan,188,60]}
df = pd.DataFrame(scores, index=['Simon','Allen','Jimmy','Peter'])
df

       Math English  History
Simon  90.0      60     33.0
Allen   NaN      70      NaN
Jimmy  70.0      90    188.0
Peter  80.0      50     60.0

a.請將English裡有問題的’90’改為數字90

In [40]:
df['English'] = pd.to_numeric(df['English'])
df.English

Simon    60
Allen    70
Jimmy    90
Peter    50
Name: English, dtype: int64

b.請將History裡的188，改成88

In [35]:
df.loc['Jimmy','History'] = 88
df.History

Simon    33.0
Allen     NaN
Jimmy    88.0
Peter    60.0
Name: History, dtype: float64

c.請將遺漏值nan，設為各自欄位的平均值(提示用fillna)

In [36]:
df = df.fillna(df.mean())
df

       Math  English    History
Simon  90.0     60.0  33.000000
Allen  80.0     70.0  60.333333
Jimmy  70.0     90.0  88.000000
Peter  80.0     50.0  60.000000

d.請確認資料型態（轉換後）

In [41]:
df.dtypes

Math       float64
English      int64
History    float64
dtype: object